"""Added new field to memo model

Revision ID: 54dd84587d35
Revises: 6f9f0f071cf4
Create Date: 2022-07-17 22:39:49.725757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54dd84587d35'
down_revision = '6f9f0f071cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo', sa.Column('linked_image', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memo', 'linked_image')
    # ### end Alembic commands ###
