"""added like

Revision ID: ca62baf92545
Revises: 63de4a35ce38
Create Date: 2022-07-29 23:06:27.651744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca62baf92545'
down_revision = '63de4a35ce38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo', sa.Column('liked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memo', 'liked')
    # ### end Alembic commands ###
